apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: pycon2019
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: kafka
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: pycon2019
spec:
  selector:
     matchLabels:
        app: kafka
  serviceName: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: kafka
        imagePullPolicy: IfNotPresent
        image: 'bitnami/kafka:2'
        resources:
          requests:
            memory: "600Mi"
            cpu: 500m
        ports:
        - containerPort: 9092
          name: kafka
        env:
          - name: KAFKA_CFG_ZOOKEEPER_CONNECT
            value: "zookeeper.pycon2019.svc.cluster.local:2181"
          - name: ALLOW_PLAINTEXT_LISTENER
            value: "yes"
